# Example: .github/workflows/node.js.yml

# Name of the workflow
name: Node.js CI

# Specifies when the workflow should be triggered
on:
  # Triggers the workflow on 'push' events to the 'main' branch
  push:
    branches:
      - main
  # Also triggers the workflow on 'pull_request' events targeting the 'main' branch
  pull_request:
    branches:
      - main

# Defines the jobs that the workflow will execute
jobs:
  # Job identifier, can be any name (here it's 'build')
  build:
    # Specifies the type of virtual host environment (runner) to use
    runs-on: ubuntu-latest

    # Strategy for running the jobs - this section is useful for testing across multiple environments
    strategy:
      # A matrix build strategy to test against multiple versions of Node.js
      matrix:
        node-version: [18.x, 20.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        # Sets up the specified version of Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Initialize init
          # Runs tests as defined in the project's package.json
        run: npm init

      - name: Install dependencies
        # Installs node modules as specified in the project's package-lock.json
        run: npm ci

      - name: Build project
        # This command will only run if a build script is defined in the package.json
        run: npm run build --if-present

      - name: Run tests
        # Runs tests as defined in the project's package.json
        run: npm test
